version: '1'
services:
  app:
    build: .
    container_name:  myapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    environment:
      - SQLITE_PATH=/app/app_dev.db
    volumes:
      - .:/app